//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Common.StageControllers.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS.Common.StageControllers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CPC-1B,1
        ///CPC-2B,2
        ///CPC-3B,3
        ///CPC-1C,1
        ///CPC-2C,2
        ///CPC-3C,3
        ///CPC-1BT,1
        ///CPC-1CT,1
        ///CPC-1CS,1
        ///CPC-2CS,2
        ///CPC-3CS,3
        ///CPC-1CH,1
        ///CPC-2CH,2
        ///CPC-3CH,3
        ///CPC-1D,1
        ///CPC-2D,2
        ///CPC-3D,3
        ///CPC-1DN,1
        ///CPC-2DN,2
        ///CPC-3DN,3
        ///CAT-I,2
        ///CAT-II,2
        ///CAT-E1,1
        ///CAT-E2,2
        ///CAT-E3,3
        ///CAT-ED1,1
        ///CAT-ED2,2
        ///CAT-ED3,3
        ///CAT-C1,1
        ///CAT-C2,2
        ///CAT-C3,3
        ///CAT-D1,1
        ///CAT-D2,2
        ///CAT-D3,3
        ///MMC-2,2
        ///MMC-XP,2
        ///MS-C2,2
        ///MS-P4,4
        ///QT-CD1/QT-CD1-35,1
        ///QT-CM2/QT-CM2-35,2
        ///QT-CN6,6
        ///QT-ADL1/QT-ADL1-35,1
        ///QT-ADM2/QT-ADM2-35,2
        ///QT-ADM3/QT-ADM3-35,3
        ///QT-AMH [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControllerSpec {
            get {
                return ResourceManager.GetString("ControllerSpec", resourceCulture);
            }
        }
    }
}
